[theme]
base = "dark"
primaryColor = "#4A90E2"
backgroundColor = "#1E1E1E"
secondaryBackgroundColor = "#2D2D2D"
textColor = "#FFFFFF"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
